### ISSUE TITLE
Trying to compile a .so version for linux

### ISSUE THREAD

**Issue by Willdrick** [ReynoldsCahoon/WotLK-Mumble-Positional-Voice#1]
I'm biting way bigger than my mouth allows me to. Any pointers on how to compile it for linux? Tried pulling mumble's git and using the header files that come in there but I keep getting errors

**Comment by ReynoldsCahoon** [comment]
What specific steps have you taken?

**Comment by Willdrick** [comment]
I tried using gcc in place, adding the .h files that it kept asking... that was going nowhere (tbh I have no idea what I'm doing).
Then I decided to just overwrite your version's cpp file with the one from mumble's git, but couldn't get it to compile, I'm knee deep in -devel libs I'll never use, and still nothing. 
The furthest I got was manually setting all cmake flags to off (except plugins) but nothing happens

![Captura desde 2024-05-02 17-45-03](https://github.com/ReynoldsCahoon/WotLK-Mumble-Positional-Voice/assets/2455158/10a3c2ef-4be6-4540-9cba-fa1cac688840)

**Comment by ReynoldsCahoon** [comment]
As per the documentation, this works specifically for Mumble 1.3.4 (or versions previous to 1.4.0) because of changes to Mumble's Plugin API.
